name: PR_tests

on:
  pull_request:
    branches:
    - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: add execution permission to gradlew file
        run: chmod u+x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: UnitTest_Reports
          path: app/build/reports/tests

  Assemble-debug:
    name: Build debug apk file
    runs-on: ubuntu-latest
    needs:
      - Unit-test

    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: add execution permission to gradlew file
        run: chmod u+x gradlew

      - name: Build apk
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: chilly-app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  Run-screenshot-tests:
    name: Run screenshot tests
    runs-on: ubuntu-latest
    needs:
      - Assemble-debug

    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add execution permission to gradlew file
        run: chmod u+x gradlew

      - name: Run screenshot tests
        run: ./gradlew validateDebugScreenshotTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: ScreenshotTest_Reports
          path: app/build/reports/screenshotTest