name: PR_unit_tests

on:
  pull_request:
    branches:
    - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up jdk 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: add execution permission to gradlew file
        run: chmod u+x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Download test reports
        uses: actions/upload-artifact@v4
        with:
          name: UnitTest_Reports
          path: app/build/reports/tests